# Generated by Django 3.2.2 on 2022-02-23 23:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamestore', '0009_alter_customuser_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='friends',
            field=models.ManyToManyField(blank=True, default={}, related_name='_gamestore_customuser_friends_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
