# Generated by Django 3.2.2 on 2022-02-24 01:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamestore', '0011_remove_customuser_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='follows',
            field=models.ManyToManyField(blank=True, related_name='_gamestore_customuser_follows_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
