# Generated by Django 3.2.2 on 2022-02-24 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamestore', '0013_alter_customuser_follows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=32, unique=True),
        ),
    ]
