# Generated by Django 3.2.2 on 2022-02-26 11:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamestore', '0014_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='follows',
            field=models.ManyToManyField(blank=True, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='game',
            name='supported_platforms',
            field=models.ManyToManyField(blank=True, related_name='supported_games', to='gamestore.Platform'),
        ),
        migrations.AlterField(
            model_name='game',
            name='user_id',
            field=models.ManyToManyField(blank=True, related_name='games', to=settings.AUTH_USER_MODEL),
        ),
    ]
